/* Shared buyer/seller address control. Google resolves the building; THM preserves condo units. */
(() => {
  const cities=['Richmond Hill','East Gwillimbury','Whitchurch-Stouffville','New Tecumseth','Newmarket','Mississauga','Brampton','Burlington','Pickering','Clarington','Toronto','Vaughan','Markham','Aurora','Oakville','Milton','Whitby','Oshawa','Ajax','King'];
  const nonAddress=value=>/^(?:https?:\/\/|[a-z]\d{7,9}$)/i.test(String(value||'').trim());
  function split(value){
    let street=String(value||'').trim(),unit=''; if(nonAddress(street))return {street,unit};
    for(const city of cities){const re=new RegExp('(?:,|\\s)'+city.replace(/ /g,'\\s+')+'(?:[,\\s]*(?:ON|Ontario|Canada|[CEW]\\d{2}|[A-Z]\\d[A-Z]\\s?\\d[A-Z]\\d))*[,\\s]*$','i');const m=street.match(re);if(m){street=street.slice(0,m.index).trim().replace(/,$/,'')+', '+city;break;}}
    const first=street.match(/^(?:(?:unit|suite|apt|apartment|#)\s*)?([a-z0-9]+)\s*[-–—]\s*(\d+[a-z]?\s+.+)$/i)||street.match(/^(?:unit|suite|apt|apartment|#)\s*([a-z0-9-]+)\s*,?\s+(\d+[a-z]?\s+.+)$/i);
    if(first){unit=first[1];street=first[2];}
    const explicit=street.match(/(?:,?\s+(?:unit|suite|apt|apartment)\s*|\s*#\s*)([a-z0-9-]+)(?=\s*,|\s*$|\s+[a-z])/i);
    if(explicit){unit=explicit[1];street=street.slice(0,explicit.index)+street.slice(explicit.index+explicit[0].length);}
    if(!unit){const tail=street.match(/\b(st(?:reet)?|rd|road|ave(?:nue)?|dr(?:ive)?|cres(?:cent)?|circ(?:le)?|blvd|boulevard|crt|court|ct|ln|lane|pkwy|parkway|way|trail|tr|place|pl|terrace|ter)\.?\s+(?:(?:[nsew]|north|south|east|west)\s+)?(\d+[a-z]?|ph\d*)(?=\s*,|\s*$|\s+[a-z])/i);if(tail){unit=tail[2];const end=tail.index+tail[0].length;street=street.slice(0,end-unit.length).trimEnd()+street.slice(end);}}
    return {street:street.replace(/\s+,/g,',').replace(/\s{2,}/g,' ').trim(),unit:String(unit||'').toUpperCase()};
  }
  function combine(value,unit){if(nonAddress(value))return String(value).trim();const p=split(value),u=String(unit||p.unit||'').trim().replace(/^(?:unit|suite|apt|#)\s*/i,'').toUpperCase(),comma=p.street.indexOf(',');return u?(comma<0?`${p.street} Unit ${u}`:`${p.street.slice(0,comma)} Unit ${u}${p.street.slice(comma)}`):p.street;}
  function attach({input,panel,status,onChange=()=>{}}){
    let timer,controller,sequence=0,rows=[],active=-1,pending=null,session=crypto.randomUUID(),disabled=false,failedChoice=false;
    const list=panel.querySelector('[role=listbox]'),note=panel.querySelector('[role=status]'),credit=panel.querySelector('.address-attribution');
    input.setAttribute('role','combobox');input.setAttribute('aria-autocomplete','list');input.setAttribute('aria-expanded','false');input.setAttribute('aria-controls',list.id);
    const close=()=>{panel.hidden=true;active=-1;input.setAttribute('aria-expanded','false');input.removeAttribute('aria-activedescendant');};
    const cancel=()=>{clearTimeout(timer);controller?.abort();sequence++;close();}; const say=m=>{note.textContent=m;};
    const post=async(path,body,signal)=>{const r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body),signal});const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||'Suggestions are unavailable. You can enter the address yourself.');return d;};
    function highlight(i){active=i;[...list.children].forEach((el,n)=>el.setAttribute('aria-selected',String(n===i)));if(list.children[i]){input.setAttribute('aria-activedescendant',list.children[i].id);list.children[i].scrollIntoView({block:'nearest'});}}
    async function select(index){
      const row=rows[index];if(!row)return; const entered=split(input.value),enteredUnit=entered.unit;
      if(row.city){input.value=combine(entered.street.replace(/,.*$/,'')+', '+row.city,enteredUnit);failedChoice=false;cancel();onChange();status.textContent='City selected. Continue to find your home.';input.focus();return;}
      cancel();const current=sequence;input.setAttribute('aria-busy','true');
      pending=(async()=>{try{const data=await post('/api/address-selection',{placeId:row.placeId,sessionToken:session},AbortSignal.timeout(6500));if(current!==sequence)return;if(!data.available||!data.address)throw new Error('Suggestions are unavailable. You can enter the address yourself.');failedChoice=false;input.value=combine(data.address,enteredUnit||data.unit);input.setCustomValidity('');THMInputs.error(input,'');onChange();status.textContent=split(input.value).unit?'Address and condo unit selected.':'Address selected. If this is a condo, you can add the unit number in the same box.';input.focus();}catch(e){if(current===sequence){failedChoice=true;status.textContent=e.message;}}finally{if(current===sequence){input.removeAttribute('aria-busy');session=crypto.randomUUID();}}})();await pending;pending=null;
    }
    function renderRows(){list.replaceChildren();active=-1;rows.forEach((row,index)=>{const option=document.createElement('li');option.id=list.id+'-'+index;option.setAttribute('role','option');option.setAttribute('aria-selected','false');option.tabIndex=-1;option.textContent=row.label;let committed=false;const commit=e=>{e.preventDefault();e.stopPropagation();if(committed)return;committed=true;select(index);};option.addEventListener('pointerdown',commit);option.addEventListener('touchstart',commit,{passive:false});option.addEventListener('click',commit);list.append(option);});}
    async function suggest(){const parsed=split(input.value),q=parsed.street;if(disabled||nonAddress(q)||!/^\d+[a-z]?\s+[a-z]/i.test(q)||q.replace(/[^a-z]/ig,'').length<3)return;const current=sequence,lc=new AbortController();controller=lc;const deadline=setTimeout(()=>lc.abort(),6500);try{const data=await post('/api/address-suggestions',{q,sessionToken:session},lc.signal);if(current!==sequence||document.activeElement!==input)return;if(!data.available){disabled=true;close();return;}rows=data.suggestions||[];renderRows();say(rows.length?(parsed.unit?`Unit ${parsed.unit} will be kept — choose the building address.`:'Tap your address below.'):'No suggestions yet. Keep typing, or enter the full street address.');credit.hidden=!rows.length;panel.hidden=false;input.setAttribute('aria-expanded','true');}catch{if(current===sequence)close();}finally{clearTimeout(deadline);}}
    input.addEventListener('input',()=>{failedChoice=false;cancel();input.removeAttribute('aria-busy');input.setCustomValidity('');THMInputs.error(input,'');onChange();timer=setTimeout(suggest,250);});
    input.addEventListener('keydown',e=>{if(e.key==='Escape'){cancel();return;}if(panel.hidden||!rows.length)return;if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();highlight((active+(e.key==='ArrowDown'?1:active<0?0:-1)+rows.length)%rows.length);}else if(e.key==='Enter'&&active>=0){e.preventDefault();select(active);}else if(e.key==='Tab')close();});
    document.addEventListener('pointerdown',e=>{if(e.target!==input&&!panel.contains(e.target))close();});
    input.addEventListener('blur',()=>setTimeout(()=>{if(!panel.matches(':hover'))close();},120));
    return {async prepare(){await pending;if(failedChoice){input.focus();return null;}cancel();return combine(input.value,'');},set(value){failedChoice=false;cancel();input.value=combine(value,'');input.setCustomValidity('');THMInputs.error(input,'');},requireUnit(){const p=split(input.value);input.value=p.street;input.setCustomValidity('Add your condo unit in this same box, for example “405-36 Forest Manor Rd” or “36 Forest Manor Rd Unit 405”.');THMInputs.check(input);input.focus();},showCities(cs){cancel();rows=cs.map(city=>({city,label:city}));renderRows();credit.hidden=true;say('This street address matches more than one city. Which is yours?');panel.hidden=false;input.setAttribute('aria-expanded','true');input.focus();},cancel};
  }
  window.THMAddress={split,combine,attach};
})();