const $=id=>document.getElementById(id);let token="",agentData=[];
$("loginForm").addEventListener("submit",e=>{e.preventDefault();token=$("key").value.trim();load();});$("refresh").addEventListener("click",load);
document.querySelectorAll(".tab").forEach(b=>b.addEventListener("click",()=>{document.querySelectorAll(".tab").forEach(x=>x.classList.toggle("active",x===b));["leadsView","agentsView"].forEach(id=>$(id).hidden=id!==b.dataset.view);}));
$("addAgent").addEventListener("click",()=>openAgent());$("cancelAgent").addEventListener("click",closeAgent);$("agentForm").addEventListener("submit",saveAgent);
async function api(path,options={}){const r=await fetch(path,{...options,headers:{Authorization:`Bearer ${token}`,...(options.headers||{})},cache:"no-store"}),b=await r.json().catch(()=>null);if(!r.ok)throw new Error(b?.error||"Request failed.");return b;}
async function load(){if(!token)return;$("error").textContent="";try{const[l,a]=await Promise.all([api("/api/admin/leads"),api("/api/admin/agents")]);$("login").hidden=true;$("dashboard").hidden=false;agentData=a.agents||[];renderLeads(l.leads||[]);renderAgents();}catch(e){$("error").textContent=e.message;}}
function renderLeads(leads){const overdue=leads.filter(x=>x.status==="new"&&x.first_response_due_at&&new Date(x.first_response_due_at)<new Date()).length,queued=leads.reduce((n,x)=>n+(x.automation_jobs||[]).filter(j=>j.status==="queued").length,0),blocked=leads.reduce((n,x)=>n+(x.automation_jobs||[]).filter(j=>["blocked","failed"].includes(j.status)).length,0);$("stats").innerHTML=stat("New",leads.filter(x=>x.status==="new").length)+stat("SLA overdue",overdue)+stat("Jobs queued",queued)+stat("Blocked / failed",blocked);$("updated").textContent=`Updated ${new Date().toLocaleTimeString()}`;$("leads").innerHTML=leads.length?leads.map(card).join(""):"<p>No leads yet.</p>";document.querySelectorAll("select[data-id]").forEach(s=>s.addEventListener("change",()=>updateLead(s.dataset.id,s.value)));}
function renderAgents(){$("agents").innerHTML=agentData.length?agentData.map(a=>`<article class="agent ${a.active?"":"inactive"}"><div><span>${esc(a.code)} · Order ${a.assignment_order}</span><h2>${esc(a.display_name)}</h2><p>${a.email?esc(a.email):"No email"} · ${a.mobile?esc(a.mobile):"No mobile"}</p></div><div><b>${a.active?"Active":"Inactive"}</b><button data-edit="${a.id}">Edit</button></div></article>`).join(""):"<p>No agents configured.</p>";document.querySelectorAll("[data-edit]").forEach(b=>b.addEventListener("click",()=>openAgent(agentData.find(a=>a.id===b.dataset.edit))));}
function openAgent(a=null){$("agentForm").hidden=false;$("agentFormTitle").textContent=a?"Edit agent":"Add agent";$("agentId").value=a?.id||"";$("agentName").value=a?.display_name||"";$("agentEmail").value=a?.email||"";$("agentMobile").value=a?.mobile||"";$("agentOrder").value=a?.assignment_order||"";$("agentActive").checked=a?.active!==false;$("agentError").textContent="";document.querySelector(".order-field").hidden=!a;$("agentName").focus();}function closeAgent(){$("agentForm").hidden=true;}
async function saveAgent(e){e.preventDefault();const id=$("agentId").value,payload={display_name:$("agentName").value,email:$("agentEmail").value,mobile:$("agentMobile").value,active:$("agentActive").checked};if(id)payload.assignment_order=Number($("agentOrder").value);try{await api(id?`/api/admin/agents/${id}`:"/api/admin/agents",{method:id?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});closeAgent();await load();}catch(e){$("agentError").textContent=e.message;}}
function stat(label,value){return `<article><span>${label}</span><strong>${value}</strong></article>`}function card(x){const a=x.agents||{},report=(x.property_reports||[])[0],jobs=x.automation_jobs||[];return `<article class="lead"><div class="leadtop"><div><span>${esc(x.lead_mode||"lead")} · ${date(x.created_at)}</span><h2>${esc(x.name)} — ${esc(x.resolved_address||"Property")}</h2><p><a href="tel:${attr(x.mobile)}">${esc(x.mobile)}</a>${x.email?` · <a href="mailto:${attr(x.email)}">${esc(x.email)}</a>`:""}</p></div><select data-id="${x.id}">${["new","contacted","appointment_pending","appointment_confirmed","closed","lost"].map(v=>`<option ${x.status===v?"selected":""}>${v}</option>`).join("")}</select></div><div class="meta"><span>Agent <b>${esc(a.display_name||a.code||"Unassigned")}</b></span><span>Stage <b>${esc(x.stage)}</b></span><span>Response due <b>${date(x.first_response_due_at)}</b></span><span>Report <b>${esc(report?.status||"not queued")}</b></span></div><div class="jobs">${jobs.map(j=>`<span class="${j.status}">${esc(j.job_type)}: ${esc(j.status)}</span>`).join("")}</div></article>`}async function updateLead(id,status){await api(`/api/admin/leads/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({status})});load();}function date(v){return v?new Date(v).toLocaleString("en-CA",{timeZone:"America/Toronto"}):"—"}function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}function attr(v){return esc(v).replace(/`/g,"&#96;")}
