const $=id=>document.getElementById(id);let token="",agentData=[],leadData=[],manualRequestKey=null;
$("loginForm").addEventListener("submit",e=>{e.preventDefault();token=$("key").value.trim();load();});$("refresh").addEventListener("click",load);
document.querySelectorAll(".tab").forEach(b=>b.addEventListener("click",()=>{document.querySelectorAll(".tab").forEach(x=>x.classList.toggle("active",x===b));["leadsView","agentsView","settingsView"].forEach(id=>$(id).hidden=id!==b.dataset.view);}));
$("addAgent").addEventListener("click",()=>openAgent());$("cancelAgent").addEventListener("click",closeAgent);$("agentForm").addEventListener("submit",saveAgent);$("settingsForm").addEventListener("submit",saveSettings);
async function api(path,options={}){const r=await fetch(path,{...options,headers:{Authorization:`Bearer ${token}`,...(options.headers||{})},cache:"no-store"}),b=await r.json().catch(()=>null);if(!r.ok)throw new Error(b?.error||"Request failed.");return b;}
async function load(){if(!token)return;$("error").textContent="";try{const[l,a,s]=await Promise.all([api("/api/admin/leads"),api("/api/admin/agents"),api("/api/admin/settings")]);$("login").hidden=true;$("dashboard").hidden=false;agentData=a.agents||[];$("ownerEmail").value=s.settings?.owner_notification_email||"";leadData=l.leads||[];renderLeads(leadData);renderAgents();}catch(e){$("error").textContent=e.message;$("dashboardError").textContent=e.message;}}
function renderLeads(leads){
  const showing=x=>x.showing_requested || (x.metadata?.lead_mode || x.lead_mode)==='showing';
  $('stats').innerHTML=stat('New',leads.filter(x=>x.status==='new').length)+stat('Report only',leads.filter(x=>!showing(x)).length)+stat('Showing requests',leads.filter(x=>showing(x)&&x.status!=='appointment_confirmed').length)+stat('Confirmed',leads.filter(x=>x.status==='appointment_confirmed').length);
  $('updated').textContent=`Updated ${new Date().toLocaleTimeString()}`;
  const filter=$('leadFilter').value;
  const visible=leads.filter(x=>filter==='report'?!showing(x):filter==='showing'?showing(x):filter==='confirmed'?x.status==='appointment_confirmed':true);
  if(filter==='confirmed')visible.sort((a,b)=>Date.parse(a.confirmed_showing_at)-Date.parse(b.confirmed_showing_at));
  $('leads').innerHTML=visible.length?visible.map(card).join(''):'<p>No matching leads.</p>';
  document.querySelectorAll('select[data-status-id]').forEach(s=>s.addEventListener('change',()=>updateLead(s.dataset.statusId,{status:s.value}).catch(e=>{alert(e.message);load();})));
  document.querySelectorAll('select[data-agent-id]').forEach(s=>s.addEventListener('change',()=>assignLead(s.dataset.agentId,s.value,s)));
  document.querySelectorAll('[data-remove-lead]').forEach(b=>b.addEventListener('click',()=>removeLead(b.dataset.removeLead,b)));
  document.querySelectorAll('[data-confirm-lead]').forEach(form=>form.addEventListener('submit',e=>{e.preventDefault();confirmAppointment(form.dataset.confirmLead,form);}));
}
$('leadFilter').addEventListener('change',()=>renderLeads(leadData));
$('addLead').addEventListener('click',()=>{$('manualLeadForm').reset();manualRequestKey=crypto.randomUUID();$('manualLeadForm').hidden=false;$('manualError').textContent='';$('manualName').focus();});
$('cancelLead').addEventListener('click',()=>{$('manualLeadForm').hidden=true;});
$('manualLeadForm').addEventListener('submit',async e=>{e.preventDefault();if(!$('manualLeadForm').reportValidity())return;const property=$('manualProperty').value.trim(),generate=$('manualGenerate').checked,showing=$('manualShowing').checked;if((generate||showing)&&!property){$('manualError').textContent='Choose a property for a report or showing.';return;}$('manualSave').disabled=true;try{await api('/api/admin/leads',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:$('manualName').value,mobile:$('manualMobile').value,email:$('manualEmail').value,property_input:property,listing_key:/^[A-Z]\d{7,9}$/i.test(property)?property.toUpperCase():null,showing_requested:showing,showing_timing:showing?'asap':'report',lead_mode:showing?'showing':'buyer_report',generate_report:generate,request_key:manualRequestKey})});$('manualLeadForm').hidden=true;await load();}catch(e){$('manualError').textContent=e.message;}finally{$('manualSave').disabled=false;}});
async function removeLead(id,button){if(!confirm('Remove this lead, its saved report and queued jobs? Already sent emails cannot be recalled. This cannot be undone.'))return;button.disabled=true;try{await api(`/api/admin/leads/${id}`,{method:'DELETE'});await load();}catch(e){alert(e.message);}finally{button.disabled=false;}}
async function confirmAppointment(id,form){if(!form.reportValidity())return;const button=form.querySelector('button');button.disabled=true;try{await updateLead(id,{status:'appointment_confirmed',showing_date:form.querySelector('[name=date]').value,showing_time:form.querySelector('[name=time]').value});}catch(e){alert(e.message);}finally{button.disabled=false;}}
function renderAgents(){$("agents").innerHTML=agentData.length?agentData.map(a=>`<article class="agent ${a.active?"":"inactive"}"><div><span>${esc(a.code)} · Order ${a.assignment_order}</span><h2>${esc(a.display_name)}</h2><p>${a.email?esc(a.email):"No email"} · ${a.mobile?esc(a.mobile):"No mobile"}</p></div><div><b>${a.active?"Available":"Unavailable"}</b><button data-edit="${a.id}">Edit</button></div></article>`).join(""):"<p>No agents configured.</p>";document.querySelectorAll("[data-edit]").forEach(b=>b.addEventListener("click",()=>openAgent(agentData.find(a=>a.id===b.dataset.edit))));}
function agentOptions(selected){return `<option value="">Choose an agent…</option>`+agentData.filter(a=>a.active||a.id===selected).map(a=>`<option value="${a.id}" ${a.id===selected?"selected":""}>${esc(a.display_name)}${a.email||a.mobile?"":" — missing destination"}</option>`).join("")}
function timing(v){return({asap:"As soon as possible",today:"Today, if available",within_24h:"Within 24 hours",seller_curious:"Just curious",seller_0_3:"0–3 months",seller_3_6:"3–6 months",seller_6_12:"6–12 months"})[v]||String(v||"—").replaceAll("_"," ")}
function calendarParts(value){if(!value)return {date:'',time:''};const p=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Toronto',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(new Date(value)).reduce((a,p)=>(a[p.type]=p.value,a),{});return {date:`${p.year}-${p.month}-${p.day}`,time:`${p.hour}:${p.minute}`};}
function card(x){
 const a=x.agents||null,report=Array.isArray(x.property_reports)?x.property_reports[0]:x.property_reports,jobs=x.automation_jobs||[],p=report?.report_payload||{},v=p.valuation||{},n=p.narrative||{};
 const showing=x.showing_requested || (x.metadata?.lead_mode||x.lead_mode)==='showing', preferred=calendarParts(x.preferred_showing_at),busy=jobs.some(j=>j.status==='processing');
 const reportView=report?.status==='ready'?`<details class="report-preview"><summary>View AI property report</summary><div><b>${esc(v.available?`${money(v.low)} – ${money(v.high)} · ${v.confidence||''} confidence`:'Range unavailable')}</b><p>${esc(n.executive_summary||'')}</p><small>${esc((p.comparables||[]).length)} sold comparable(s) · ${date(report.generated_at)}</small></div></details>`:'';
 const calendar=showing?`<div class="appointment-admin"><b>${x.confirmed_showing_at&&x.status==='appointment_confirmed'?`Confirmed: ${date(x.confirmed_showing_at)} · Toronto time`:`Requested: ${x.preferred_showing_at?date(x.preferred_showing_at)+' · Toronto time':esc(timing(x.showing_timing))}`}</b>${x.status!=='appointment_confirmed'?`<form data-confirm-lead="${x.id}"><label>Confirmed date<input type="date" name="date" required value="${attr(preferred.date)}"></label><label>Time · Toronto<input type="time" name="time" min="09:00" max="20:30" step="1800" required value="${attr(preferred.time)}"></label><button type="submit">Confirm &amp; email buyer</button></form><small>Confirm availability with the listing side first. The buyer receives the final time and a calendar option.</small>`:''}</div>`:'';
 return `<article class="lead"><div class="leadtop"><div><span>${showing?'Showing + report':esc(x.metadata?.lead_mode==='seller'?'Seller review':'Report / enquiry')} · ${date(x.created_at)}</span><h2>${esc(x.name)} — ${esc(x.resolved_address||x.metadata?.resolved_address||'Property')}</h2><p><a href="tel:${attr(x.mobile)}">${esc(x.mobile)}</a> · <a href="mailto:${attr(x.email)}">${esc(x.email)}</a></p></div><select aria-label="Lead status" data-status-id="${x.id}">${['new','contacted','appointment_pending',...(x.status==='appointment_confirmed'?['appointment_confirmed']:[]),'closed','lost'].map(v=>`<option ${x.status===v?'selected':''}>${v}</option>`).join('')}</select></div><div class="assignment"><label for="agent-${x.id}">Assign to</label><select id="agent-${x.id}" data-agent-id="${x.id}" class="${a?'':'unassigned'}">${agentOptions(a?.id)}</select></div>${calendar}<div class="meta"><span>Agent <b>${esc(a?.display_name||'Awaiting admin')}</b></span><span>Stage <b>${esc(x.stage)}</b></span><span>Report <b>${esc(report?.status||'not requested')}</b></span></div>${reportView}<div class="jobs">${jobs.map(j=>`<span class="${esc(j.status)}">${esc(j.job_type)}: ${esc(j.status)}</span>`).join('')}</div><button class="remove-lead" data-remove-lead="${x.id}" ${busy?'disabled title="Wait for active jobs to finish"':''}>Remove lead</button></article>`;
}
async function assignLead(id,agentId,select){if(!agentId)return;select.disabled=true;try{await updateLead(id,{owner_agent_id:agentId});}catch(e){alert(e.message);await load();}finally{select.disabled=false;}}
async function updateLead(id,payload){await api(`/api/admin/leads/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});await load();}
async function saveSettings(e){e.preventDefault();$("settingsMessage").textContent="";try{await api("/api/admin/settings",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({owner_notification_email:$("ownerEmail").value})});$("settingsMessage").textContent="Saved.";}catch(e){$("settingsMessage").textContent=e.message;}}
function openAgent(a=null){$("agentForm").hidden=false;$("agentFormTitle").textContent=a?"Edit agent":"Add agent";$("agentId").value=a?.id||"";$("agentName").value=a?.display_name||"";$("agentEmail").value=a?.email||"";$("agentMobile").value=a?.mobile||"";$("agentOrder").value=a?.assignment_order||"";$("agentActive").checked=a?.active!==false;$("agentError").textContent="";document.querySelector(".order-field").hidden=!a;$("agentName").focus();}function closeAgent(){$("agentForm").hidden=true;}
async function saveAgent(e){e.preventDefault();const id=$("agentId").value,payload={display_name:$("agentName").value,email:$("agentEmail").value,mobile:$("agentMobile").value,active:$("agentActive").checked};if(id)payload.assignment_order=Number($("agentOrder").value);try{await api(id?`/api/admin/agents/${id}`:"/api/admin/agents",{method:id?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});closeAgent();await load();}catch(e){$("agentError").textContent=e.message;}}
function stat(label,value){return `<article><span>${label}</span><strong>${value}</strong></article>`}function date(v){return v?new Date(v).toLocaleString("en-CA",{timeZone:"America/Toronto"}):"—"}function money(v){const n=Number(v);return Number.isFinite(n)&&n>0?new Intl.NumberFormat("en-CA",{style:"currency",currency:"CAD",maximumFractionDigits:0}).format(n):"—"}function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}function attr(v){return esc(v).replace(/`/g,"&#96;")}
