const $=id=>document.getElementById(id);let token="",agentData=[];
$("loginForm").addEventListener("submit",e=>{e.preventDefault();token=$("key").value.trim();load();});$("refresh").addEventListener("click",load);
document.querySelectorAll(".tab").forEach(b=>b.addEventListener("click",()=>{document.querySelectorAll(".tab").forEach(x=>x.classList.toggle("active",x===b));["leadsView","agentsView","settingsView"].forEach(id=>$(id).hidden=id!==b.dataset.view);}));
$("addAgent").addEventListener("click",()=>openAgent());$("cancelAgent").addEventListener("click",closeAgent);$("agentForm").addEventListener("submit",saveAgent);$("settingsForm").addEventListener("submit",saveSettings);
async function api(path,options={}){const r=await fetch(path,{...options,headers:{Authorization:`Bearer ${token}`,...(options.headers||{})},cache:"no-store"}),b=await r.json().catch(()=>null);if(!r.ok)throw new Error(b?.error||"Request failed.");return b;}
async function load(){if(!token)return;$("error").textContent="";try{const[l,a,s]=await Promise.all([api("/api/admin/leads"),api("/api/admin/agents"),api("/api/admin/settings")]);$("login").hidden=true;$("dashboard").hidden=false;agentData=a.agents||[];$("ownerEmail").value=s.settings?.owner_notification_email||"";renderLeads(l.leads||[]);renderAgents();}catch(e){$("error").textContent=e.message;}}
function renderLeads(leads){const overdue=leads.filter(x=>x.status==="new"&&x.first_response_due_at&&new Date(x.first_response_due_at)<new Date()).length,unassigned=leads.filter(x=>!x.agents).length,blocked=leads.reduce((n,x)=>n+(x.automation_jobs||[]).filter(j=>["blocked","failed"].includes(j.status)).length,0);$("stats").innerHTML=stat("New",leads.filter(x=>x.status==="new").length)+stat("Awaiting assignment",unassigned)+stat("SLA overdue",overdue)+stat("Blocked / failed",blocked);$("updated").textContent=`Updated ${new Date().toLocaleTimeString()}`;$("leads").innerHTML=leads.length?leads.map(card).join(""):"<p>No leads yet.</p>";document.querySelectorAll("select[data-status-id]").forEach(s=>s.addEventListener("change",()=>updateLead(s.dataset.statusId,{status:s.value})));document.querySelectorAll("select[data-agent-id]").forEach(s=>s.addEventListener("change",()=>assignLead(s.dataset.agentId,s.value,s)));}
function renderAgents(){$("agents").innerHTML=agentData.length?agentData.map(a=>`<article class="agent ${a.active?"":"inactive"}"><div><span>${esc(a.code)} · Order ${a.assignment_order}</span><h2>${esc(a.display_name)}</h2><p>${a.email?esc(a.email):"No email"} · ${a.mobile?esc(a.mobile):"No mobile"}</p></div><div><b>${a.active?"Available":"Unavailable"}</b><button data-edit="${a.id}">Edit</button></div></article>`).join(""):"<p>No agents configured.</p>";document.querySelectorAll("[data-edit]").forEach(b=>b.addEventListener("click",()=>openAgent(agentData.find(a=>a.id===b.dataset.edit))));}
function agentOptions(selected){return `<option value="">Choose an agent…</option>`+agentData.filter(a=>a.active||a.id===selected).map(a=>`<option value="${a.id}" ${a.id===selected?"selected":""}>${esc(a.display_name)}${a.email||a.mobile?"":" — missing destination"}</option>`).join("")}
function timing(v){return({asap:"As soon as possible",today:"Today, if available",within_24h:"Within 24 hours",seller_curious:"Just curious",seller_0_3:"0–3 months",seller_3_6:"3–6 months",seller_6_12:"6–12 months"})[v]||String(v||"—").replaceAll("_"," ")}
function card(x){const a=x.agents||null,report=Array.isArray(x.property_reports)?x.property_reports[0]:x.property_reports,jobs=x.automation_jobs||[],p=report?.report_payload||{},v=p.valuation||{},n=p.narrative||{},reportView=report?.status==="ready"?`<details class="report-preview"><summary>View AI property report</summary><div><b>${esc(v.available?`${money(v.low)} – ${money(v.high)} · ${v.confidence||""} confidence`:"Range unavailable")}</b><p>${esc(n.executive_summary||"")}</p><small>${esc((p.comparables||[]).length)} recent sold comparable(s) · Generated ${date(report.generated_at)}</small></div></details>`:"";return `<article class="lead"><div class="leadtop"><div><span>${esc(x.lead_mode||"lead")} · ${date(x.created_at)}</span><h2>${esc(x.name)} — ${esc(x.resolved_address||x.metadata?.resolved_address||"Property")}</h2><p><a href="tel:${attr(x.mobile)}">${esc(x.mobile)}</a> · <a href="mailto:${attr(x.email)}">${esc(x.email)}</a></p><div class="timing">Requested time: <b>${esc(timing(x.showing_timing))}</b></div></div><select data-status-id="${x.id}">${["new","contacted","appointment_pending","appointment_confirmed","closed","lost"].map(v=>`<option ${x.status===v?"selected":""}>${v}</option>`).join("")}</select></div><div class="assignment"><label for="agent-${x.id}">Assign property to</label><select id="agent-${x.id}" data-agent-id="${x.id}" class="${a?"":"unassigned"}">${agentOptions(a?.id)}</select></div><div class="meta"><span>Agent <b>${esc(a?.display_name||a?.code||"Awaiting admin")}</b></span><span>Stage <b>${esc(x.stage)}</b></span><span>Response due <b>${x.first_response_due_at?date(x.first_response_due_at):"Starts after assignment"}</b></span><span>Report <b>${esc(report?.status||"not queued")}</b></span></div>${reportView}<div class="jobs">${jobs.map(j=>`<span class="${j.status}">${esc(j.job_type)}: ${esc(j.status)}</span>`).join("")}</div></article>`}
async function assignLead(id,agentId,select){if(!agentId)return;select.disabled=true;try{await updateLead(id,{owner_agent_id:agentId});}catch(e){alert(e.message);await load();}finally{select.disabled=false;}}
async function updateLead(id,payload){await api(`/api/admin/leads/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});await load();}
async function saveSettings(e){e.preventDefault();$("settingsMessage").textContent="";try{await api("/api/admin/settings",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({owner_notification_email:$("ownerEmail").value})});$("settingsMessage").textContent="Saved.";}catch(e){$("settingsMessage").textContent=e.message;}}
function openAgent(a=null){$("agentForm").hidden=false;$("agentFormTitle").textContent=a?"Edit agent":"Add agent";$("agentId").value=a?.id||"";$("agentName").value=a?.display_name||"";$("agentEmail").value=a?.email||"";$("agentMobile").value=a?.mobile||"";$("agentOrder").value=a?.assignment_order||"";$("agentActive").checked=a?.active!==false;$("agentError").textContent="";document.querySelector(".order-field").hidden=!a;$("agentName").focus();}function closeAgent(){$("agentForm").hidden=true;}
async function saveAgent(e){e.preventDefault();const id=$("agentId").value,payload={display_name:$("agentName").value,email:$("agentEmail").value,mobile:$("agentMobile").value,active:$("agentActive").checked};if(id)payload.assignment_order=Number($("agentOrder").value);try{await api(id?`/api/admin/agents/${id}`:"/api/admin/agents",{method:id?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});closeAgent();await load();}catch(e){$("agentError").textContent=e.message;}}
function stat(label,value){return `<article><span>${label}</span><strong>${value}</strong></article>`}function date(v){return v?new Date(v).toLocaleString("en-CA",{timeZone:"America/Toronto"}):"—"}function money(v){const n=Number(v);return Number.isFinite(n)&&n>0?new Intl.NumberFormat("en-CA",{style:"currency",currency:"CAD",maximumFractionDigits:0}).format(n):"—"}function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}function attr(v){return esc(v).replace(/`/g,"&#96;")}
