import {esc,human,money,renovation,cleanNotes,sellerFields} from './admin-view-model.js';
const agent=l=>(Array.isArray(l.agents)?l.agents[0]:l.agents)?.display_name||'Unassigned';
export function leadExportRecord(l){
 const p=l.property_snapshot?.sellerProfile||{},r=renovation(p),m=l.seller_marketing,v=l.report?.valuation||{};
 return {'Lead ID':l.id,'Full Name':l.name||'','Email':l.email||'','Phone':l.mobile||'','Property Address':l.resolved_address||'','Request':human(l.lead_mode),'Status':human(l.status),'Assigned Agent':agent(l),'Received At':l.created_at||'','Archived At':l.archived_at||'','Source':l.source||'','Showing Requested':l.showing_requested?'Yes':'No','Preferred Showing':l.preferred_showing_at||'','Confirmed Showing':l.confirmed_showing_at||'',
 'Seller Minimum CAD':p.targetMin??'','Seller Maximum CAD':p.targetMax??'','Earlier Target CAD':p.targetPrice??'','Renovation Percent':r.value??'','Renovation Description':r.label,'Home Type':p.homeType||'','City':p.city||'','Community':p.community||'','Size Sq Ft':p.sizeBand||'','Bedrooms':p.beds??'','Bedrooms Below Ground':p.belowBeds??'','Basement':human(p.basement),'Separate Entrance':human(p.entrance),'Kitchens':p.kitchens??'','Postal Code':p.postal||'','Selling Timeline':human(p.timing),'Owner Notes':cleanNotes(p),
 'Report Status':l.report?.status||'','Report Generated At':l.report?.generated_at||'','THM Estimate Low CAD':v.available!==false?v.low??'':'','THM Estimate CAD':v.available!==false?v.midpoint??v.estimated_market_value??'':'','THM Estimate High CAD':v.available!==false?v.high??'':'',
 'Marketing Consent':m?.consented?(m.suppressedAt?'Unsubscribed':'Opted in'):'Not opted in','Marketing Consent At':m?.consentAt||'','Marketing Consent Wording':m?.wording||'','Marketing Consent Version':m?.version||'','Marketing Consent Source':m?.source||'','Marketing Unsubscribed At':m?.suppressedAt||'','Strategy Email Status':m?.emailStatus||'Not requested','Strategy Email Sent At':m?.sentAt||''};
}
export function csvCell(value){let text=String(value??'');if(/^[\s]*[=+\-@]/.test(text)||/^[\t\r\n]/.test(text))text="'"+text;return '"'+text.replaceAll('"','""')+'"';}
export function leadsCSV(leads){const rows=leads.map(leadExportRecord);if(!rows.length)return '\ufeff';return '\ufeff'+[Object.keys(rows[0]).map(csvCell).join(','),...rows.map(row=>Object.values(row).map(csvCell).join(','))].join('\r\n')+'\r\n';}
const cardEscape=value=>String(value??'').replaceAll('\\','\\\\').replace(/\r\n|\r|\n/g,'\\n').replaceAll(';','\\;').replaceAll(',','\\,');
function fold(line){let rows=[],part='',bytes=0;for(const ch of line){const n=new TextEncoder().encode(ch).length;if(bytes+n>75){rows.push(part);part=' ';bytes=1;}part+=ch;bytes+=n;}rows.push(part);return rows.join('\r\n');}
export function leadsVCards(leads){return leads.map(l=>{const record=leadExportRecord(l),parts=String(l.name||'').trim().split(/\s+/),given=parts.shift()||'',family=parts.join(' '),note=Object.entries(record).filter(([key,val])=>val!==''&&!['Full Name','Email','Phone'].includes(key)).map(([key,val])=>key+': '+val).join('\n');return ['BEGIN:VCARD','VERSION:3.0','N:'+cardEscape(family)+';'+cardEscape(given)+';;;','FN:'+cardEscape(l.name),'UID:urn:uuid:'+cardEscape(l.id),...(l.email?['EMAIL;TYPE=INTERNET:'+cardEscape(l.email)]:[]),...(l.mobile?['TEL;TYPE=CELL:'+cardEscape(l.mobile)]:[]),'NOTE:'+cardEscape(note),'END:VCARD'].map(fold).join('\r\n');}).join('\r\n')+'\r\n';}
export function leadsJSON(leads){return JSON.stringify({format:'THM lead export',version:1,exportedAt:new Date().toISOString(),consentNote:'Marketing permission and unsubscribe status must be retained when importing elsewhere.',leads:leads.map(l=>({...l,export_fields:leadExportRecord(l)}))},null,2);}
export function leadsPrintHTML(leads){return '<!doctype html><html lang="en"><head><meta charset="utf-8"><title>THM Lead Export</title><style>body{font:14px/1.5 Arial,sans-serif;color:#203b3c;margin:32px}h1,h2{font-family:Georgia,serif;font-weight:400}h1{font-size:28px}h2{font-size:20px}article{page-break-after:always}article:last-child{page-break-after:auto}.brand{font-size:11px;letter-spacing:2px;color:#a55e40}dl{display:grid;grid-template-columns:1fr 1fr;gap:14px}dt{font-size:11px;color:#64736c}dd{margin:0;overflow-wrap:anywhere}section{border-top:1px solid #dce3dc;padding-top:12px;margin-top:20px}@page{size:A4;margin:16mm}@media print{body{margin:0}section{break-inside:avoid}h1,h2{break-after:avoid}}</style></head><body>'+leads.map(l=>{const p=l.property_snapshot?.sellerProfile,m=l.seller_marketing,r=renovation(p||{}),v=l.report?.valuation||{},dl=pairs=>'<dl>'+pairs.map(([k,v])=>'<div><dt>'+esc(k)+'</dt><dd>'+esc(v??'Not provided')+'</dd></div>').join('')+'</dl>';return '<article><p class="brand">TORONTO HOUSE MARKET · PRIVATE LEAD RECORD</p><h1>'+esc(l.name)+'</h1><p>'+esc(l.resolved_address||'Contact only')+'</p>'+dl([['Email',l.email],['Phone',l.mobile],['Request',human(l.lead_mode)],['Status',human(l.status)],['Assigned agent',agent(l)],['Received',l.created_at]])+(p?'<section><h2>Seller’s submitted details</h2>'+dl([...sellerFields(p),['Renovation level',r.value===null?'Not provided':r.value+'% · '+r.label],['Notes',cleanNotes(p)||'Not provided']])+'</section>':'')+'<section><h2>Saved report summary</h2>'+dl([['Report',human(l.report?.status)],['Low estimate',v.available===false?'Unavailable':money(v.low)],['Estimated value',v.available===false?'Unavailable':money(v.midpoint??v.estimated_market_value)],['High estimate',v.available===false?'Unavailable':money(v.high)]])+'</section><section><h2>Marketing permission</h2>'+dl([['Permission',m?.consented?(m.suppressedAt?'Unsubscribed':'Opted in'):'Not opted in'],['Recorded',m?.consentAt],['Strategy email',human(m?.emailStatus)],['Consent wording',m?.wording]])+'<p>Keep consent and unsubscribe status when importing this contact elsewhere.</p></section></article>';}).join('')+'</body></html>';}
