import app from './worker-v16.js';
const AMPRE='https://query.ampre.ca/odata';
const OPENAI='https://api.openai.com/v1/responses';
const MODEL='gpt-5.6-luna';
export default {async fetch(request,env,ctx){const u=new URL(request.url);if(u.pathname==='/api/internal/v71-random-qa-select')return selectBatch(env);if(u.pathname==='/api/internal/v71-random-qa-report')return reportOne(env,u.searchParams.get('listingKey'));return app.fetch(request,env,ctx)},scheduled(c,e,x){return app.scheduled(c,e,x)}};
const auth=t=>({Authorization:`Bearer ${t}`,Accept:'application/json'}), norm=s=>String(s||'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim(), clean=v=>typeof v==='string'?v.trim()||null:null, num=v=>{const x=Number(v);return Number.isFinite(x)?x:null}, money=v=>{const x=Number(v);return Number.isFinite(x)&&x>0?x:null}, odata=s=>String(s||'').replace(/'/g,"''");
const json=(b,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{'Content-Type':'application/json','Cache-Control':'no-store'}});
async function jf(url,init={}){const r=await fetch(url,{...init,signal:AbortSignal.timeout(15000)});if(!r.ok)throw new Error(`${r.status}`);return r.json()}
async function recent(env,limit=1800){const h=auth(env.AMPRE_VOW_TOKEN);const cu=new URL(`${AMPRE}/Property`);cu.search=new URLSearchParams({'$count':'true','$top':'1'});let count=0;try{count=Number((await jf(cu,{headers:h}))['@odata.count'])||0}catch{}let skip=Math.max(0,count-limit),rows=[];while(rows.length<limit){const u=new URL(`${AMPRE}/Property`);u.search=new URLSearchParams({'$top':'100',...(skip?{'$skip':String(skip)}:{})});let d;try{d=await jf(u,{headers:h})}catch{break}const p=Array.isArray(d.value)?d.value:[];rows.push(...p);if(p.length<100)break;skip+=100}return rows}
function category(r){const t=norm(`${r.PropertySubType||''} ${r.PropertyType||''}`);if(/condo apartment|apartment condo|condominium apartment/.test(t)||(t.includes('apartment')&&/condo|condominium/.test(t)))return'condo_apt';if(/condo townhouse|townhouse condo|condominium townhouse/.test(t))return'condo_town';if(/semi detached/.test(t))return'semi';if(/detached/.test(t)&&!/semi/.test(t))return'detached';if(/att row townhouse|row townhouse|freehold townhouse|townhouse/.test(t)&&!/condo|condominium/.test(t))return'freehold_town';return null}
function active(r){const s=`${r.StandardStatus||''} ${r.MlsStatus||''} ${r.ContractStatus||''} ${r.TransactionType||''}`;return /active|for sale|new/i.test(s)&&!/lease|rent/i.test(s)&&money(r.ListPrice)>50000}
function gta(r){return /(toronto|mississauga|brampton|vaughan|richmond hill|markham|aurora|newmarket|oakville|burlington|milton|pickering|ajax|whitby|oshawa|caledon|king|stouffville)/.test(norm(`${r.City||''} ${r.CityRegion||''} ${r.UnparsedAddress||''}`))}
function area(r){return clean(r.CityRegion)||clean(r.City)||String(r.PostalCode||'').slice(0,3)||'Unknown'}
function shuffle(a,seed=9172026){let x=seed>>>0,b=[...a];for(let i=b.length-1;i>0;i--){x=(1664525*x+1013904223)>>>0;const j=x%(i+1);[b[i],b[j]]=[b[j],b[i]]}return b}
async function selectBatch(env){if(!env.AMPRE_VOW_TOKEN)return json({ok:false,error:'VOW unavailable'},503);const rows=await recent(env);const pool=shuffle(rows.filter(r=>active(r)&&gta(r)&&category(r)&&r.ListingKey&&r.UnparsedAddress));const wants=[['detached',2],['semi',2],['freehold_town',1],['condo_apt',3],['condo_town',2]],out=[],used=new Set();for(const [k,cnt]of wants){let n=0;for(const r of pool){if(n>=cnt)break;if(category(r)!==k)continue;const a=area(r);if(used.has(a))continue;out.push(r);used.add(a);n++}if(n<cnt){for(const r of pool){if(n>=cnt)break;if(category(r)!==k||out.some(x=>x.ListingKey===r.ListingKey))continue;out.push(r);n++}}}return json({ok:out.length===10,count:out.length,listings:out.map(r=>({category:category(r),listingKey:r.ListingKey,address:r.UnparsedAddress,city:r.City,community:r.CityRegion,propertyType:r.PropertySubType||r.PropertyType,listPrice:money(r.ListPrice),beds:num(r.BedroomsTotal),baths:num(r.BathroomsTotalInteger),size:r.LivingAreaRange||num(r.BuildingAreaTotal)}))},out.length===10?200:422)}
async function byKey(env,key){const r=await fetch(`${AMPRE}/Property('${encodeURIComponent(key)}')`,{headers:auth(env.AMPRE_VOW_TOKEN),signal:AbortSignal.timeout(15000)});return r.ok?r.json():null}
async function tail(env,filter,limit=700){const h=auth(env.AMPRE_VOW_TOKEN);const cu=new URL(`${AMPRE}/Property`);cu.search=new URLSearchParams({'$filter':filter,'$count':'true','$top':'1'});let count=0;try{count=Number((await jf(cu,{headers:h}))['@odata.count'])||0}catch{}let skip=Math.max(0,count-limit),rows=[];while(rows.length<limit){const u=new URL(`${AMPRE}/Property`);u.search=new URLSearchParams({'$filter':filter,'$top':'100',...(skip?{'$skip':String(skip)}:{})});let d;try{d=await jf(u,{headers:h})}catch{break}const p=Array.isArray(d.value)?d.value:[];rows.push(...p);if(p.length<100)break;skip+=100}return rows}
function sold(s,rs){const subj=norm(s.UnparsedAddress),condo=/condo|condominium/i.test(`${s.PropertyType||''} ${s.PropertySubType||''}`),seen=new Set();return rs.filter(r=>{const id=r.ListingKey;if(!id||seen.has(id))return false;seen.add(id);const st=`${r.StandardStatus||''} ${r.MlsStatus||''} ${r.ContractStatus||''} ${r.TransactionType||''}`,p=money(r.ClosePrice||r.SoldPrice||r.SalePrice||r.FinalSalePrice),d=new Date(r.PurchaseContractDate||r.SoldDate||r.CloseDate||r.ModificationTimestamp||''),rc=/condo|condominium/i.test(`${r.PropertyType||''} ${r.PropertySubType||''}`);return /sold|closed|deal firm/i.test(st)&&!/lease|rent/i.test(st)&&p&&Number.isFinite(d.getTime())&&(Date.now()-d.getTime())/864e5<=900&&norm(r.UnparsedAddress)!==subj&&rc===condo}).map(r=>({id:String(r.ListingKey),address:r.UnparsedAddress,type:r.PropertySubType||r.PropertyType,community:r.CityRegion,postal:r.PostalCode,soldPrice:money(r.ClosePrice||r.SoldPrice||r.SalePrice||r.FinalSalePrice),soldDate:new Date(r.PurchaseContractDate||r.SoldDate||r.CloseDate||r.ModificationTimestamp).toISOString().slice(0,10),beds:num(r.BedroomsTotal),baths:num(r.BathroomsTotalInteger),size:r.LivingAreaRange||null,lotWidth:num(r.LotWidth),lotDepth:num(r.LotDepth),parking:num(r.ParkingTotal),basement:Array.isArray(r.Basement)?r.Basement.join(' · '):r.Basement||null,remarks:String(r.PublicRemarks||'').slice(0,500)})).sort((a,b)=>Date.parse(b.soldDate)-Date.parse(a.soldDate)).slice(0,60)}
async function broad(env,s){const qs=[],community=clean(s.CityRegion),postal=String(s.PostalCode||'').replace(/\s/g,'').slice(0,3).toUpperCase(),city=clean(s.City)?.replace(/^Toronto\s+[CEW]\d{2}$/i,'Toronto');if(community&&!/^(toronto )?[cew]\d{2}$/i.test(community))qs.push(`contains(CityRegion,'${odata(community)}')`);if(/^[A-Z]\d[A-Z]$/.test(postal))qs.push(`startswith(PostalCode,'${postal}')`);if(city)qs.push(`contains(UnparsedAddress,'${odata(city)}')`);const all=[];for(const q of [...new Set(qs)].slice(0,3)){all.push(...await tail(env,q));if(sold(s,all).length>=35)break}return sold(s,all)}
const schema={type:'object',additionalProperties:false,properties:{confidence:{type:'string',enum:['Moderate','Low','Limited']},market_read:{type:'string'},buyer_strategy:{type:'string'},comparables:{type:'array',minItems:1,maxItems:6,items:{type:'object',additionalProperties:false,properties:{id:{type:'string'},weight:{type:'number',minimum:.1,maximum:1},adjusted_indication:{type:'number'},selection_reason:{type:'string'},adjustment_reason:{type:'string'},adjustment_basis:{type:'string',enum:['evidence_supported','professional_judgment','none']}},required:['id','weight','adjusted_indication','selection_reason','adjustment_reason','adjustment_basis']}}},required:['confidence','market_read','buyer_strategy','comparables']};
async function expert(env,s,cands){const subject={address:s.UnparsedAddress,type:s.PropertySubType||s.PropertyType,community:s.CityRegion,city:s.City,postal:s.PostalCode,listPrice:money(s.ListPrice),beds:num(s.BedroomsTotal),baths:num(s.BathroomsTotalInteger),size:s.LivingAreaRange,area:num(s.BuildingAreaTotal),lotWidth:num(s.LotWidth),lotDepth:num(s.LotDepth),parking:num(s.ParkingTotal),basement:s.Basement,remarks:String(s.PublicRemarks||'').slice(0,900)};const r=await fetch(OPENAI,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${env.OPENAI_API_KEY}`},signal:AbortSignal.timeout(30000),body:JSON.stringify({model:MODEL,reasoning:{effort:'medium'},input:[{role:'system',content:'Act as an experienced GTA residential buyer Realtor using Version 7.1 Expert Comp logic. Select the economically most relevant REAL sold MLS properties from the supplied pool. Do not mechanically prioritize any single field. Recorded sold prices are facts and must never be altered. adjusted_indication is your reasoned indication for the subject after material differences. Return JSON only.'},{role:'user',content:JSON.stringify({subject,candidates:cands})}],text:{format:{type:'json_schema',name:'v71_batch',strict:true,schema}}})});const d=await r.json().catch(()=>null);if(!r.ok)throw new Error(`OpenAI ${r.status}`);const t=d?.output_text||d?.output?.flatMap(x=>x.content||[]).filter(x=>x.type==='output_text').map(x=>x.text||'').join('')||'';return JSON.parse(t)}
function med(a){const b=[...a].sort((x,y)=>x-y),m=Math.floor(b.length/2);return b.length%2?b[m]:(b[m-1]+b[m])/2}const round=x=>Math.round(x/10000)*10000;
async function reportOne(env,key){if(!key)return json({ok:false,error:'listingKey required'},400);if(!env.AMPRE_VOW_TOKEN||!env.OPENAI_API_KEY)return json({ok:false,error:'Bindings unavailable'},503);const s=await byKey(env,key);if(!s)return json({ok:false,error:'Listing not found'},404);const cands=await broad(env,s);if(!cands.length)return json({ok:true,listingKey:key,address:s.UnparsedAddress,candidateCount:0,selectedCount:0,valuation:null,confidence:'Unavailable'});const e=await expert(env,s,cands),map=new Map(cands.map(c=>[c.id,c])),final=(e.comparables||[]).map(x=>({...map.get(x.id),...x})).filter(x=>x.soldPrice),vals=final.map(x=>Number(x.adjusted_indication)).filter(Number.isFinite);let valuation=null;if(vals.length>=2){const mid=med(vals),spread=Math.max(...vals)-Math.min(...vals),margin=Math.max(mid*(vals.length>=4?.06:.09),spread*.35);valuation={low:round(mid-margin),midpoint:round(mid),high:round(mid+margin)}}return json({ok:true,version:'7.1',model:MODEL,category:category(s),listingKey:key,address:s.UnparsedAddress,city:s.City,community:s.CityRegion,propertyType:s.PropertySubType||s.PropertyType,listPrice:money(s.ListPrice),beds:num(s.BedroomsTotal),baths:num(s.BathroomsTotalInteger),size:s.LivingAreaRange||num(s.BuildingAreaTotal),candidateCount:cands.length,selectedCount:final.length,confidence:e.confidence,valuation,marketRead:e.market_read,buyerStrategy:e.buyer_strategy,comparables:final.map(x=>({address:x.address,type:x.type,soldPrice:x.soldPrice,soldDate:x.soldDate,size:x.size,adjustedIndication:x.adjusted_indication,reason:x.selection_reason}))})}
