import app from './worker-v18-qa.js';
const AMPRE='https://query.ampre.ca/odata';
const auth=t=>({Authorization:`Bearer ${t}`,Accept:'application/json'}),norm=s=>String(s||'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim(),clean=v=>typeof v==='string'?v.trim()||null:null,num=v=>{const x=Number(v);return Number.isFinite(x)?x:null},money=v=>{const x=Number(v);return Number.isFinite(x)&&x>0?x:null},odata=s=>String(s||'').replace(/'/g,"''");
const json=(b,s=200)=>new Response(JSON.stringify(b),{status:s,headers:{'Content-Type':'application/json','Cache-Control':'no-store'}});
export default {async fetch(request,env,ctx){const u=new URL(request.url);if(u.pathname==='/api/internal/v71-random-qa-select')return selectBatch(env);return app.fetch(request,env,ctx)},scheduled(c,e,x){return app.scheduled(c,e,x)}};
async function jf(url,init={}){const r=await fetch(url,{...init,signal:AbortSignal.timeout(15000)});if(!r.ok)throw new Error(`${r.status}`);return r.json()}
async function tail(env,filter,limit=350){const h=auth(env.AMPRE_VOW_TOKEN);const cu=new URL(`${AMPRE}/Property`);cu.search=new URLSearchParams({'$filter':filter,'$count':'true','$top':'1'});let count=0;try{count=Number((await jf(cu,{headers:h}))['@odata.count'])||0}catch{}let skip=Math.max(0,count-limit),rows=[];while(rows.length<limit){const u=new URL(`${AMPRE}/Property`);u.search=new URLSearchParams({'$filter':filter,'$top':'100',...(skip?{'$skip':String(skip)}:{})});let d;try{d=await jf(u,{headers:h})}catch{break}const p=Array.isArray(d.value)?d.value:[];rows.push(...p);if(p.length<100)break;skip+=100}return rows}
function category(r){const t=norm(`${r.PropertySubType||''} ${r.PropertyType||''}`);if(/condo apartment|apartment condo|condominium apartment/.test(t)||(t.includes('apartment')&&/condo|condominium/.test(t)))return'condo_apt';if(/condo townhouse|townhouse condo|condominium townhouse/.test(t))return'condo_town';if(/semi detached/.test(t))return'semi';if(/detached/.test(t)&&!/semi/.test(t))return'detached';if(/att row townhouse|row townhouse|freehold townhouse|townhouse/.test(t)&&!/condo|condominium/.test(t))return'freehold_town';return null}
function active(r){const s=`${r.StandardStatus||''} ${r.MlsStatus||''} ${r.ContractStatus||''} ${r.TransactionType||''}`;return /active|for sale|new|available/i.test(s)&&!/lease|rent|leased/i.test(s)&&money(r.ListPrice)>50000}
function area(r){return clean(r.CityRegion)||clean(r.City)||String(r.PostalCode||'').slice(0,3)||'Unknown'}
function shuffle(a,seed=9172026){let x=seed>>>0,b=[...a];for(let i=b.length-1;i>0;i--){x=(1664525*x+1013904223)>>>0;const j=x%(i+1);[b[i],b[j]]=[b[j],b[i]]}return b}
async function selectBatch(env){if(!env.AMPRE_VOW_TOKEN)return json({ok:false,error:'VOW unavailable'},503);const communities=['Annex','Willowdale','East York','Mimico','High Park','Leaside','Vellore','Maple','Patterson','Kleinburg','Oak Ridges','Langstaff','Unionville','Cornell','Wismer','Erin Mills','Churchill Meadows','Port Credit','Meadowvale','City Centre','Bram East','Credit Valley','Glen Abbey','Bronte','River Oaks','Alton','Orchard','Duffin Heights','Amberlea','Brooklin','Windfields','Woodland Hill'];let rows=[];for(const q of communities){try{rows.push(...await tail(env,`contains(CityRegion,'${odata(q)}')`,250))}catch{}}
const byId=new Map();for(const r of rows)if(r?.ListingKey)byId.set(r.ListingKey,r);const pool=shuffle([...byId.values()].filter(r=>active(r)&&category(r)&&r.UnparsedAddress));const wants=[['detached',2],['semi',2],['freehold_town',1],['condo_apt',3],['condo_town',2]],out=[],used=new Set();for(const [k,cnt]of wants){let n=0;for(const r of pool){if(n>=cnt)break;if(category(r)!==k)continue;const a=area(r);if(used.has(a))continue;out.push(r);used.add(a);n++}if(n<cnt){for(const r of pool){if(n>=cnt)break;if(category(r)!==k||out.some(x=>x.ListingKey===r.ListingKey))continue;out.push(r);n++}}}
const counts={};for(const r of pool)counts[category(r)]=(counts[category(r)]||0)+1;return json({ok:out.length===10,count:out.length,poolCounts:counts,listings:out.map(r=>({category:category(r),listingKey:r.ListingKey,address:r.UnparsedAddress,city:r.City,community:r.CityRegion,propertyType:r.PropertySubType||r.PropertyType,listPrice:money(r.ListPrice),beds:num(r.BedroomsTotal),baths:num(r.BathroomsTotalInteger),size:r.LivingAreaRange||num(r.BuildingAreaTotal)}))},out.length===10?200:422)}
