import app from './worker-v20.js';
import reportScheduler from './worker-v15.js';
import reportCore from './worker-v12.js';
const QA_TOKEN='v73sync-7f4d9a2c';
const AMPRE='https://query.ampre.ca/odata', OPENAI='https://api.openai.com/v1/responses', LUNA='gpt-5.6-luna';
const QA_CASES={
 '389':{job:389,report:'01217ef0-cbdf-411a-916a-68dc12592f9d',key:'W13770846'},
 '393':{job:393,report:'4f3f40e4-b35e-4021-9bf1-b009c54ff61f',key:'N13580058'}
};
export default{
 async fetch(request,env,ctx){
  const u=new URL(request.url);
  if(u.pathname==='/api/internal/v73-run-sync'&&request.method==='POST'){
   if(request.headers.get('X-THM-QA')!==QA_TOKEN)return new Response('Not found',{status:404});
   const started=Date.now();await runCore({},env);return j({ok:true,elapsed_ms:Date.now()-started});
  }
  if(u.pathname==='/api/internal/v73-fast-qa'&&request.method==='POST'){
   if(request.headers.get('X-THM-QA')!==QA_TOKEN)return new Response('Not found',{status:404});
   const c=QA_CASES[u.searchParams.get('job')];if(!c)return j({ok:false,error:'case'},400);
   try{return j(await fastQa(env,c));}catch(e){return j({ok:false,error:String(e?.message||e).slice(0,300)},500);}
  }
  return app.fetch(request,env,ctx);
 },
 async scheduled(controller,env,ctx){ctx.waitUntil(runScheduled(controller,env));}
};
async function drain(call){const pending=[];const proxy={waitUntil(p){pending.push(Promise.resolve(p));}};await call(proxy);let rounds=0;while(pending.length&&rounds<30){const batch=pending.splice(0);await Promise.allSettled(batch);rounds++;}}
async function runCore(controller,env){await drain(proxy=>reportCore.scheduled(controller,{...env,OPENAI_MODEL:LUNA,OPENAI_EXTERNAL_COMP_SEARCH:'false',RESEND_API_KEY:null},proxy));}
async function runScheduled(controller,env){await drain(proxy=>reportScheduler.scheduled(controller,{...env,OPENAI_MODEL:LUNA,RESEND_API_KEY:null},proxy));await drain(proxy=>app.scheduled(controller,{...env,RESEND_API_KEY:null},proxy));}

async function fastQa(env,c){
 if(!env.AMPRE_VOW_TOKEN||!env.OPENAI_API_KEY||!env.SUPABASE_SERVICE_ROLE_KEY)throw new Error('missing binding');
 const sr=await fetch(`${AMPRE}/Property('${encodeURIComponent(c.key)}')`,{headers:auth(env.AMPRE_VOW_TOKEN),signal:AbortSignal.timeout(12000)});if(!sr.ok)throw new Error(`subject ${sr.status}`);const s=await sr.json();
 const pool=await broadPool(s,env.AMPRE_VOW_TOKEN);if(pool.length<2){await saveUnavailable(env,c,s,pool.length);return{ok:true,job:c.job,candidates:pool.length,selected:0,available:false};}
 const x=await luna(env,s,pool),by=new Map(pool.map(z=>[z.id,z]));
 const comps=(x.comparables||[]).map(q=>{const b=by.get(String(q.id));return b?{...b,adjustedIndication:num(q.adjusted_indication)||b.soldPrice,expertSelectionReason:q.selection_reason||null,expertAdjustmentReason:q.adjustment_reason||null,expertAdjustmentBasis:q.adjustment_basis||'professional_judgment',weight:Math.max(.1,Math.min(1,num(q.weight)||.5)),evidenceSource:'ampre_vow'}:null}).filter(Boolean).slice(0,6);
 if(comps.length<2){await saveUnavailable(env,c,s,pool.length);return{ok:true,job:c.job,candidates:pool.length,selected:comps.length,available:false};}
 const vals=comps.map(z=>({v:z.adjustedIndication,w:z.weight||1})).sort((a,b)=>a.v-b.v),mv=round(weightedMedian(vals)),disp=vals.reduce((a,z)=>a+z.w*Math.abs(z.v-mv)/mv,0)/vals.reduce((a,z)=>a+z.w,0),quality=comps.length>=4&&disp<.10?'Strong':comps.length>=3?'Moderate':'Limited',pct=Math.max(quality==='Strong'?.04:quality==='Moderate'?.055:.08,Math.min(.11,disp*1.35)),low=round(mv*(1-pct)),high=round(mv*(1+pct));
 const facts={address:s.UnparsedAddress||null,list_price:num(s.ListPrice),property_type:s.PropertySubType||s.PropertyType||null,beds:num(s.BedroomsTotal),baths:num(s.BathroomsTotalInteger),living_area:s.LivingAreaRange||null,parking:num(s.ParkingTotal),neighbourhood:s.CityRegion||null,listing_key:s.ListingKey||c.key,status:s.StandardStatus||s.MlsStatus||null};
 const payload={report_type:'THM AI buyer intelligence brief',version:7.3,version_label:'Toronto House Market Version 7.3',generated_by:'V7.3 isolated real-MLS QA recovery',facts,valuation:{available:true,estimated_market_value:mv,market_value:mv,midpoint:mv,low,high,likely_market_range:{low,high},confidence:quality,basis:`${comps.length} genuine sold MLS records selected from a broad ${pool.length}-sale VOW pool and reconciled by Luna. Recorded sold prices were not altered.`,methodology:'Broad VOW discovery; housing type, building, size, layout and micro-market are relevance signals rather than hard gates.'},comparables:comps,comparable_policy:{strictEngineFirst:true,expertMode:true,candidateCount:pool.length,selectedCount:comps.length,externalEvidenceCount:0,broadDiscovery:true},expert_comp_mode:{used:true,model:LUNA,candidateCount:pool.length,selectedCount:comps.length,externalEvidenceCount:0,confidence:quality,marketRead:x.market_read||null},evidence_quality:{label:quality,candidate_count:pool.length,selected_count:comps.length,same_subtype_selected:comps.filter(z=>norm(z.propertySubType)===norm(facts.property_type)).length,same_building_selected:0,large_adjustment_count:comps.filter(z=>Math.abs(z.adjustedIndication-z.soldPrice)/z.soldPrice>=.15).length,philosophy:'Broad discovery; structural attributes are relevance signals, not hard filters.'},model_policy:{primary:LUNA,terra_review:false,terra_threshold:'exceptionally complex only',complexity_score:0,complexity_flags:[]},decision_summary:{headline:'Estimated Market Value',estimated_market_value:mv,likely_market_range:{low,high},asking_price:facts.list_price,asking_vs_value_pct:facts.list_price?Math.round((facts.list_price-mv)/mv*1000)/10:null,evidence_confidence:quality,market_read:x.market_read||null,strategy:x.buyer_strategy||null},narrative:{executive_summary:x.market_read||null,market_read:x.market_read||null,buyer_strategy:x.buyer_strategy||null,strengths:[],risks:[],inspection_priorities:[],questions_for_realtor:[]},ai_generation:{provider:'openai',model:LUNA,fallback_used:true,expert_comp_mode:true},ai_note:'Version 7.3 · Luna first · Terra not required'};
 await complete(env,c,payload);return{ok:true,job:c.job,candidates:pool.length,selected:comps.length,emv:mv,low,high,quality};
}
async function luna(env,s,pool){const schema={type:'object',additionalProperties:false,properties:{market_read:{type:'string'},buyer_strategy:{type:'string'},comparables:{type:'array',minItems:2,maxItems:6,items:{type:'object',additionalProperties:false,properties:{id:{type:'string'},weight:{type:'number',minimum:.1,maximum:1},adjusted_indication:{type:'number'},selection_reason:{type:'string'},adjustment_reason:{type:'string'},adjustment_basis:{type:'string',enum:['evidence_supported','professional_judgment','none']}},required:['id','weight','adjusted_indication','selection_reason','adjustment_reason','adjustment_basis']}}},required:['market_read','buyer_strategy','comparables']};const subject={address:s.UnparsedAddress,type:s.PropertySubType||s.PropertyType,community:s.CityRegion,city:s.City,postal:s.PostalCode,beds:num(s.BedroomsTotal),baths:num(s.BathroomsTotalInteger),size:s.LivingAreaRange,lotWidth:num(s.LotWidth),lotDepth:num(s.LotDepth),parking:num(s.ParkingTotal),remarks:String(s.PublicRemarks||'').slice(0,800)};const r=await fetch(OPENAI,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${env.OPENAI_API_KEY}`},signal:AbortSignal.timeout(35000),body:JSON.stringify({model:LUNA,reasoning:{effort:'medium'},input:[{role:'system',content:'Act as an experienced GTA buyer Realtor performing a CMA. Select the most economically relevant REAL sold records from the supplied MLS pool. Type, subtype, building, size, bedroom count, lot and location are relevance signals, not automatic exclusion gates. Recorded sold prices are facts and must never be changed or invented. adjusted_indication is the implied subject value after explicitly reconciling material differences. Prefer same building/complex for condos when useful and same micro-market/housing form for freeholds. Return JSON only.'},{role:'user',content:JSON.stringify({subject,candidates:pool})}],text:{format:{type:'json_schema',name:'thm_v73_fast_qa',strict:true,schema}}})});const d=await r.json();if(!r.ok)throw new Error(`Luna ${r.status}: ${d?.error?.message||'failed'}`);const t=d.output_text||(d.output||[]).flatMap(a=>a.content||[]).filter(a=>a.type==='output_text').map(a=>a.text).join('');if(!t)throw new Error('Luna empty');return JSON.parse(t);}
async function broadPool(s,token){const qs=[],community=clean(s.CityRegion),postal=String(s.PostalCode||'').replace(/\s/g,'').slice(0,3).toUpperCase(),city=clean(s.City)?.replace(/^Toronto\s+[CEW]\d{2}$/i,'Toronto');if(community&&!/^(toronto )?[cew]\d{2}$/i.test(community))qs.push(`contains(CityRegion,'${odata(community)}')`);if(/^[A-Z]\d[A-Z]$/.test(postal))qs.push(`startswith(PostalCode,'${postal}')`);if(city)qs.push(`contains(UnparsedAddress,'${odata(city)}')`);const rows=[];for(const q of [...new Set(qs)].slice(0,3)){rows.push(...await tail(q,token,500));if(soldRows(s,rows).length>=35)break;}return soldRows(s,rows).slice(0,60);}
async function tail(filter,token,limit){let count=null;const cu=new URL(`${AMPRE}/Property`);cu.search=new URLSearchParams({'$filter':filter,'$count':'true','$top':'1'});try{const r=await fetch(cu,{headers:auth(token),signal:AbortSignal.timeout(8000)});if(r.ok)count=Number((await r.json())?.['@odata.count']);}catch{}let skip=Number.isSafeInteger(count)&&count>limit?count-limit:0,rows=[];while(rows.length<limit){const u=new URL(`${AMPRE}/Property`);u.search=new URLSearchParams({'$filter':filter,'$top':'100',...(skip?{'$skip':String(skip)}:{})});const r=await fetch(u,{headers:auth(token),signal:AbortSignal.timeout(9000)});if(!r.ok)break;const b=await r.json().catch(()=>null),p=Array.isArray(b?.value)?b.value:[];rows.push(...p);if(p.length<100)break;skip+=100;}return rows;}
function soldRows(s,rows){const seen=new Set(),sa=norm(s.UnparsedAddress),sc=/condo|condominium/i.test(`${s.PropertyType||''} ${s.PropertySubType||''}`);return(rows||[]).filter(r=>{const id=r?.ListingKey;if(!id||seen.has(id))return false;seen.add(id);const st=`${r.StandardStatus||''} ${r.MlsStatus||''} ${r.ContractStatus||''} ${r.TransactionType||''}`,price=num(r.ClosePrice||r.SoldPrice||r.SalePrice||r.FinalSalePrice),dt=new Date(r.PurchaseContractDate||r.SoldDate||r.CloseDate||r.ModificationTimestamp||''),cc=/condo|condominium/i.test(`${r.PropertyType||''} ${r.PropertySubType||''}`);return/sold|closed|deal firm/i.test(st)&&!/lease|rent/i.test(st)&&price>50000&&Number.isFinite(dt.getTime())&&(Date.now()-dt.getTime())/864e5<=900&&norm(r.UnparsedAddress)!==sa&&cc===sc;}).map(r=>({id:String(r.ListingKey),listingKey:String(r.ListingKey),address:clean(r.UnparsedAddress),propertySubType:clean(r.PropertySubType||r.PropertyType),community:clean(r.CityRegion),postalCode:clean(r.PostalCode),soldPrice:num(r.ClosePrice||r.SoldPrice||r.SalePrice||r.FinalSalePrice),soldDate:new Date(r.PurchaseContractDate||r.SoldDate||r.CloseDate||r.ModificationTimestamp).toISOString().slice(0,10),beds:num(r.BedroomsTotal),baths:num(r.BathroomsTotalInteger),livingAreaRange:clean(r.LivingAreaRange),lotWidth:num(r.LotWidth),lotDepth:num(r.LotDepth),parking:num(r.ParkingTotal),remarks:String(r.PublicRemarks||'').slice(0,500)})).sort((a,b)=>Date.parse(b.soldDate)-Date.parse(a.soldDate));}
async function complete(env,c,payload){const now=new Date().toISOString(),h={Prefer:'return=minimal'};let r=await db(env,`/rest/v1/property_reports?id=eq.${c.report}`,{method:'PATCH',headers:h,body:JSON.stringify({status:'ready',report_payload:payload,generated_at:now,error_message:null,updated_at:now})});if(!r.ok)throw new Error(`save report ${r.status}`);r=await db(env,`/rest/v1/automation_jobs?id=eq.${c.job}`,{method:'PATCH',headers:h,body:JSON.stringify({status:'completed',completed_at:now,locked_at:null,last_error:null,updated_at:now})});if(!r.ok)throw new Error(`save job ${r.status}`);}
async function saveUnavailable(env,c,s,n){const payload={report_type:'THM AI buyer intelligence brief',version:7.3,version_label:'Toronto House Market Version 7.3',facts:{address:s.UnparsedAddress,list_price:num(s.ListPrice),property_type:s.PropertySubType||s.PropertyType,listing_key:s.ListingKey},valuation:{available:false,estimated_market_value:null,low:null,high:null,confidence:'Limited',basis:`Only ${n} usable genuine sold candidates were recovered; THM did not fabricate a value.`},comparables:[],evidence_quality:{label:'Limited',candidate_count:n,selected_count:0},model_policy:{primary:LUNA,terra_review:false},decision_summary:{headline:'Insufficient market evidence',estimated_market_value:null,likely_market_range:{low:null,high:null},asking_price:num(s.ListPrice),evidence_confidence:'Limited'},ai_note:'Version 7.3 · value withheld because evidence was insufficient'};await complete(env,c,payload);}
function weightedMedian(a){const t=a.reduce((s,z)=>s+z.w,0);let c=0;for(const z of a){c+=z.w;if(c>=t/2)return z.v;}return a.at(-1).v;}function round(v){if(!Number.isFinite(v))return null;const s=v>=1e6?10000:5000;return Math.round(v/s)*s;}function auth(t){return{Authorization:`Bearer ${t}`,Accept:'application/json'}}function odata(v){return String(v||'').replace(/'/g,"''")}function norm(v){return String(v||'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim()}function clean(v){return typeof v==='string'?v.trim()||null:v==null?null:String(v)}function num(v){const n=Number(v);return Number.isFinite(n)&&n>0?n:null}function j(x,s=200){return new Response(JSON.stringify(x),{status:s,headers:{'Content-Type':'application/json','Cache-Control':'no-store'}})}function db(env,path,init={}){const base=env.SUPABASE_URL||'https://pwbtxyavjjotxtvegrqe.supabase.co';return fetch(`${base}${path}`,{...init,headers:{'Content-Type':'application/json',apikey:env.SUPABASE_SERVICE_ROLE_KEY,Authorization:`Bearer ${env.SUPABASE_SERVICE_ROLE_KEY}`,...(init.headers||{})}})}
