const {chromium}=require(process.env.POSTGRID_PLAYWRIGHT_PATH||'/tmp/thm-presentation-deps/node_modules/playwright');
const fs=require('fs'),http=require('http'),path=require('path'),assert=require('assert/strict');
(async()=>{
 const root=process.cwd(),server=http.createServer((req,res)=>{const p=new URL(req.url,'http://localhost').pathname;const file=path.join(root,p);if(p==='/'){res.setHeader('Content-Type','text/html');return res.end('<main><section id="prospectsView"></section></main>');}if(p.startsWith('/api/media')){res.setHeader('Content-Type','image/jpeg');return res.end(fs.readFileSync(process.env.PRESENTATION_TEST_PHOTO||'/workspace/scratch/71ad38cb9ef7/howland-seller-sample/assets/225-howland.jpg'));}if(!file.startsWith(root+'/')||!fs.existsSync(file))return res.writeHead(404).end();res.setHeader('Content-Type',p.endsWith('.js')?'text/javascript':p.endsWith('.css')?'text/css':p.endsWith('.pdf')?'application/pdf':'application/octet-stream');res.end(fs.readFileSync(file));});await new Promise(r=>server.listen(0,'127.0.0.1',r));
 const browser=await chromium.launch({headless:true,args:['--no-sandbox']}),page=await browser.newPage({viewport:{width:1365,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 try{
 await page.goto('http://127.0.0.1:'+server.address().port);await page.addStyleTag({url:'/admin-postgrid.css'});await page.addStyleTag({url:'/admin-workspace.css'});
 const photoData='data:image/jpeg;base64,'+fs.readFileSync(process.env.PRESENTATION_TEST_PHOTO||'/workspace/scratch/71ad38cb9ef7/howland-seller-sample/assets/225-howland.jpg').toString('base64');
 await page.evaluate(async(photoData)=>{
  const {initAdminPostgrid}=await import('/admin-postgrid.js');window.rows=[{listingKey:'C1',reviewProof:'proof-1',address:'261 Howland Avenue'}];window.calls=[];window.delay=false;
  window.data={ok:true,templateVersion:'approved-v1',listingKey:'C1',reviewProof:'fresh',address:'261 Howland Avenue',locality:'The Annex · Toronto',fullAddress:'261 Howland Avenue, Toronto, ON M5R 3B7',keyword:'HOWLAND',generatedAt:'2026-10-07T12:00:00Z',sales:[{address:'225 Howland Avenue',price:1736000,date:'2026-06-16',type:'Townhouse',photoKey:'test1'},{address:'170 Howland Avenue',price:2110000,date:'2026-06-14',type:'Semi-detached',photoKey:'test2'},{address:'144 Howland Avenue',price:2550000,date:'2026-05-17',type:'Semi-detached',photoKey:'test3'}]};data.sales.forEach(s=>s.photoData=photoData);data.sellerUrl='https://torontohousemarket.com/seller?'+new URLSearchParams({address:data.fullAddress});
  const create=URL.createObjectURL;URL.createObjectURL=f=>{window.pdfFile=f;return create(f);};
  window.app=initAdminPostgrid({$:id=>document.getElementById(id),esc:v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;'),getSelected:()=>rows,post:async(p,b)=>{calls.push(p);if(p.endsWith('/subject'))return {reviewProof:b.reviewProof,address:{firstName:'Current Homeowner',addressLine1:rows[0].address,city:'Toronto',provinceOrState:'ON',postalOrZip:'M5R 3B7'}};if(p.endsWith('/presentation')){if(delay)await new Promise(r=>window.release=r);return {...data};}throw Error('Unexpected write: '+p);}});
  await document.getElementById('mailPrepare').onclick();document.getElementById('mailModeCustom').checked=true;document.getElementById('mailModeCustom').onchange();
 },photoData);
 await page.locator('[data-mail-generate="0"]').click();await page.waitForFunction(()=>document.getElementById('mailStatus').textContent.includes('presentation is ready'),null,{timeout:60000});
 assert.equal(await page.evaluate(()=>calls.some(p=>p.endsWith('/create'))),false);assert.equal(await page.locator('#mailConfirm').isChecked(),false);
 fs.writeFileSync('/tmp/customized-presentation.pdf',Buffer.from(await page.evaluate(async()=>Array.from(new Uint8Array(await pdfFile.arrayBuffer())))));
 await page.screenshot({path:'/tmp/presentation-panel-desktop.png',fullPage:true});await page.setViewportSize({width:390,height:844});await page.screenshot({path:'/tmp/presentation-panel-mobile.png',fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 // A response for the removed property cannot attach its report to the new selection.
 await page.evaluate(()=>{delay=true;});await page.locator('[data-mail-generate="0"]').click();await page.waitForFunction(()=>typeof release==='function');
 await page.evaluate(()=>{rows=[{listingKey:'C2',reviewProof:'proof-2',address:'88 Other Road'}];app.selectionChanged();release();});await page.waitForFunction(()=>document.getElementById('mail-to-0-addressLine1')?.value==='88 Other Road');assert.equal(await page.locator('#mail-file-0 a').count(),0);
 // Long unit address fits, and a second QR uses its own complete address.
 await page.evaluate(async()=>{const {generatePresentation}=await import('/admin-presentation-pdf.js');data.address='Unit 1201 · 12345 Upper Highland Crescent North';data.fullAddress=data.address+', Toronto, ON M5R 3B7';data.sellerUrl='https://torontohousemarket.com/seller?'+new URLSearchParams({address:data.fullAddress});window.longFile=(await generatePresentation(data)).file;});
 fs.writeFileSync('/tmp/customized-presentation-long.pdf',Buffer.from(await page.evaluate(async()=>Array.from(new Uint8Array(await longFile.arrayBuffer())))));assert.deepEqual(errors,[]);console.log(JSON.stringify({generated:true,noMailOrders:true,staleResponseDiscarded:true,mobileOverflow:false,pdfBytes:fs.statSync('/tmp/customized-presentation.pdf').size}));
 }finally{await browser.close();await new Promise(r=>server.close(r));}
})().catch(e=>{console.error(e);process.exitCode=1;});
