import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {adminOps,listParams} from '../admin-api.js';
import {renovation,sellerFields,valuation,phone,esc} from '../admin-view-model.js';
const env={ADMIN_API_KEY:'test-admin-key',SUPABASE_SERVICE_ROLE_KEY:'test-service',SUPABASE_URL:'https://test.invalid'};
const id='aaaaaaaa-aaaa-4aaa-aaaa-aaaaaaaaaaaa';
const req=(path,body,token='test-admin-key')=>new Request('https://thm.invalid/api/admin/ops'+path,{method:body?'POST':'GET',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},...body?{body:JSON.stringify(body)}:{}});
function mockFetch(handler){const old=globalThis.fetch;globalThis.fetch=handler;return()=>{globalThis.fetch=old;};}
test('admin authorization fails closed before any database request',async()=>{const restore=mockFetch(()=>{throw Error('must not call database');});try{assert.equal((await adminOps(req('/counts',null,'wrong'),env)).status,401);assert.equal((await adminOps(req('/counts'),{...env,ADMIN_API_KEY:''})).status,401);}finally{restore();}});
test('lead filters and pagination are applied server side, without truncating to newest 100',()=>{const {params}=listParams(new URL('https://thm.invalid/?page=8&size=50&archive=1&kind=seller&status=contacted&agent=unassigned&q=Jane'),false);assert.equal(params.get('offset'),'350');assert.equal(params.get('archived_at'),'not.is.null');assert.equal(params.get('owner_agent_id'),'is.null');assert.equal(params.get('lead_mode'),'eq.seller');assert.equal(params.get('status'),'eq.contacted');assert.match(params.get('or'),/name.ilike.\*Jane\*/);});
test('all-matching job selection retains relational search and applies filters',()=>{const {params}=listParams(new URL('https://thm.invalid/?ids=1&q=Jane&status=attention&kind=generate_report'),true);assert.equal(params.get('select'),'id,leads!inner(id)');assert.equal(params.get('limit'),'1001');assert.equal(params.get('status'),'in.(queued,processing,failed,blocked)');assert.equal(params.get('job_type'),'eq.generate_report');});
test('bulk action accepts explicit IDs only and preserves per-row skips',async()=>{let calls=0;const restore=mockFetch(async(url,options)=>{calls++;assert.match(String(url),/rpc\/admin_ops_lead_action$/);assert.deepEqual(JSON.parse(options.body),{p_ids:[id],p_action:'archive'});return Response.json({results:[{id,ok:true}]});});try{assert.equal((await adminOps(req('/leads/bulk',{action:'delete',ids:['*']}),env)).status,400);assert.equal(calls,0);const data=await (await adminOps(req('/leads/bulk',{action:'archive',ids:[id]}),env)).json();assert.equal(data.results[0].ok,true);}finally{restore();}});
test('cancel jobs calls only the atomic cancellation RPC, never sending emails',async()=>{let calls=0;const restore=mockFetch(async(url,options)=>{calls++;assert.match(String(url),/rpc\/admin_ops_cancel_jobs$/);assert.deepEqual(JSON.parse(options.body),{p_ids:['123','124']});return Response.json({results:[{id:'123',ok:true},{id:'124',ok:false,reason:'Processing'}]});});try{const data=await(await adminOps(req('/jobs/cancel',{ids:['123','124']}),env)).json();assert.equal(calls,1);assert.equal(data.results.filter(x=>x.ok).length,1);}finally{restore();}});
test('creating an agent validates input and uses the atomic database operation',async()=>{const restore=mockFetch(async(url,options)=>{assert.match(String(url),/rpc\/admin_ops_create_agent$/);assert.equal(JSON.parse(options.body).p_name,'Test Agent');return Response.json({id,display_name:'Test Agent'});});try{assert.equal((await adminOps(req('/agents',{display_name:'X',email:'bad'}),env)).status,400);const response=await adminOps(req('/agents',{display_name:' Test Agent ',email:'test@example.com',active:true}),env);assert.equal(response.status,201);assert.equal((await response.json()).agent.id,id);}finally{restore();}});
test('all matching selection refuses the database row cap instead of silently selecting a partial result',async()=>{const restore=mockFetch(async()=>Response.json(Array.from({length:1000},(_,i)=>({id:String(i)})),{headers:{'content-range':'0-999/1200'}}));try{assert.equal((await adminOps(req('/jobs?ids=1'),env)).status,400);}finally{restore();}});
test('seller inputs preserve explicit zero, unknown, legacy renovation notes and expectations',()=>{assert.deepEqual(renovation({renovationPct:0}),{value:0,label:'Mostly original / dated'});assert.equal(renovation({renovationPct:null}).value,null);assert.equal(renovation({notes:'[THM_RENOVATION_PCT:65]'}).label,'Extensively renovated');const p={targetMin:900000,targetMax:1000000,renovationPct:65,beds:0,kitchens:0};const fields=Object.fromEntries(sellerFields(p));assert.equal(fields['Minimum expected price'],'$900,000');assert.equal(fields['Kitchens'],0);assert.equal(valuation({valuation:{midpoint:875000,low:820000,high:930000}}).value,875000);assert.equal(p.targetMin,900000);});
test('contact validation and HTML output cannot inject markup',()=>{assert.equal(phone('647 890 4704'),'+16478904704');assert.equal(phone('0000000000'),null);assert.equal(esc('<script>'), '&lt;script&gt;');});
test('public worker changes consist only of admin module delegation',()=>{const worker=readFileSync(new URL('../worker-v22.js',import.meta.url),'utf8');assert.match(worker,/if\(url.pathname.startsWith\('\/api\/admin\/ops\/'\)\) return adminOps/);const api=readFileSync(new URL('../admin-api.js',import.meta.url),'utf8');assert.doesNotMatch(api,/processV7ReportJobs|deliverEmailJob|api\.resend\.com/);});
