const {chromium}=require(process.env.POSTGRID_PLAYWRIGHT_PATH||'/tmp/thm-browser-deps/node_modules/playwright');
const fs=require('fs'),http=require('http'),path=require('path');
const root=process.cwd();
(async()=>{
 const server=http.createServer((req,res)=>{const name=new URL(req.url,'http://localhost').pathname.slice(1);if(!name){res.setHeader('Content-Type','text/html');res.end('<!doctype html><html><head></head><body></body></html>');return;}if(!['admin-postgrid.js','admin-postgrid.css','admin-workspace.css'].includes(name)){res.writeHead(404).end();return;}res.setHeader('Content-Type',name.endsWith('.css')?'text/css':'text/javascript');res.end(fs.readFileSync(path.join(root,name)));});await new Promise(r=>server.listen(0,'127.0.0.1',r));
 const browser=await chromium.launch({headless:true,executablePath:require('child_process').execFileSync('which',['google-chrome'],{encoding:'utf8'}).trim(),args:['--no-sandbox']});const page=await browser.newPage({viewport:{width:1365,height:1000}});let errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://127.0.0.1:'+server.address().port);
 await page.setContent('<link rel="stylesheet" href="/admin-workspace.css"><link rel="stylesheet" href="/admin-postgrid.css"><main style="max-width:1060px;margin:28px auto;padding:0 18px"><section id="prospectsView"></section></main>');
 await page.evaluate(async()=>{const {initAdminPostgrid}=await import('/admin-postgrid.js');const rows=[{listingKey:'TEST-1',reviewProof:'one',address:'24 Sample Avenue'},{listingKey:'TEST-2',reviewProof:'two',address:'58 Example Road'}];const address={addressLine1:'24 Sample Avenue',city:'Toronto',provinceOrState:'ON',postalOrZip:'M5V 2T6'};const records=[{id:'a',property:'24 Sample Avenue',recipient:{firstName:'Sample Recipient',...address},sender:{companyName:'Golestan Team'},pdfName:'Selling-Plan-and-Fees.pdf',status:'ready',postgridId:'letter_synthetic',createdAt:new Date().toISOString()},{id:'b',property:'58 Example Road',recipient:{firstName:'Example Recipient',...address},pdfName:'Custom-Seller-Plan.pdf',status:'rejected',error:'Incorrect PDF dimensions. Use 8.5 × 11-inch pages.',createdAt:new Date().toISOString()}];window.app=initAdminPostgrid({$:id=>document.getElementById(id),esc:s=>String(s??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;'),getSelected:()=>rows,post:async(p,b)=>p.endsWith('subject')?{reviewProof:'fresh',address:{...address,addressLine1:b.reviewProof==='one'?'24 Sample Avenue':'58 Example Road'}}:p.endsWith('history')?{orders:records}:p.endsWith('refresh')?{order:records.find(o=>o.id===b.id)}:{connected:true}});await document.getElementById('mailPrepare').onclick();});
 await page.screenshot({path:'/tmp/postgrid-composer-desktop.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:'/tmp/postgrid-composer-mobile.png',fullPage:true});const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);if(overflow)throw Error('Mobile overflow');
 await page.setViewportSize({width:1365,height:1000});await page.evaluate(async()=>{document.getElementById('prospectsView').hidden=true;document.getElementById('mailHistoryView').hidden=false;await window.app.loadHistory();});await page.screenshot({path:'/tmp/postgrid-history.png',fullPage:true});
 console.log(JSON.stringify({errors,mobileOverflow:overflow}));await browser.close();server.close();if(errors.length)process.exitCode=1;
})();
